=begin
#Pipedrive API v1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Pipedrive::CurrenciesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurrenciesApi' do
  before do
    # run before each test
    @instance = Pipedrive::CurrenciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrenciesApi' do
    it 'should create an instance of CurrenciesApi' do
      expect(@instance).to be_instance_of(Pipedrive::CurrenciesApi)
    end
  end

  # unit tests for currencies_get
  # Get all supported currencies
  # Returns all supported currencies in given account which should be used when saving monetary values with other objects. The &#39;code&#39; parameter of the returning objects is the currency code according to ISO 4217 for all non-custom currencies.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :term Optional search term that is searched for from currency&#39;s name and/or code.
  # @return [nil]
  describe 'currencies_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
