=begin
#Pipedrive API v1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Pipedrive::DealsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DealsApi' do
  before do
    # run before each test
    @instance = Pipedrive::DealsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DealsApi' do
    it 'should create an instance of DealsApi' do
      expect(@instance).to be_instance_of(Pipedrive::DealsApi)
    end
  end

  # unit tests for deals_delete
  # Delete multiple deals in bulk
  # Marks multiple deals as deleted.
  # @param ids Comma-separated IDs that will be deleted
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_find_get
  # Find deals by name
  # Searches all deals by their title.
  # @param term Search term to look for
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :person_id ID of the person deal is associated with.
  # @option opts [Float] :org_id ID of the organization deal is associated with.
  # @return [nil]
  describe 'deals_find_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_get
  # Get all deals
  # Returns all deals
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :user_id If supplied, only deals matching the given user will be returned.
  # @option opts [Float] :filter_id ID of the filter to use
  # @option opts [Float] :stage_id If supplied, only deals within the given stage will be returned.
  # @option opts [String] :status Only fetch deals with specific status. If omitted, all not deleted deals are fetched.
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page. Default limit is 100, maximum limit is 500.
  # @option opts [String] :sort Field names and sorting mode separated by comma (field_name_1 ASC, field_name_2 DESC). Only first-level field keys are supported (no nested keys).
  # @option opts [String] :owned_by_you When supplied, only deals owned by you are returned. However filter_id takes precedence over owned_by_you when both are supplied.
  # @return [nil]
  describe 'deals_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_activities_get
  # List activities associated with a deal
  # Lists activities associated with a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @option opts [String] :done Whether to fetch done (1) or undone (0) activities. If omitted from request, both undone and done activities are fetched.
  # @option opts [String] :exclude A comma-separated string of activity IDs to exclude from result
  # @return [nil]
  describe 'deals_id_activities_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_delete
  # Delete a deal
  # Marks a deal as deleted.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_duplicate_post
  # Duplicate deal
  # Duplicate a deal
  # @param id ID of the deal that will be duplicated
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_duplicate_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_files_get
  # List files attached to a deal
  # Lists files associated with a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @option opts [String] :include_deleted_files When enabled, the list of files will also include deleted files. Please note that trying to download these files will not work.
  # @option opts [String] :sort Field names and sorting mode separated by comma (field_name_1 ASC, field_name_2 DESC). Only first-level field keys are supported (no nested keys). Supported fields: id, user_id, deal_id, person_id, org_id, product_id, add_time, update_time, file_name, file_type, file_size, comment.
  # @return [nil]
  describe 'deals_id_files_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_flow_get
  # List updates about a deal
  # Lists updates about a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @return [nil]
  describe 'deals_id_flow_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_followers_follower_id_delete
  # Delete a follower from a deal
  # Deletes a follower from a deal.
  # @param id ID of the deal
  # @param follower_id ID of the follower
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_followers_follower_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_followers_get
  # List followers of a deal
  # Lists the followers of a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_followers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_followers_post
  # Add a follower to a deal
  # Adds a follower to a deal.
  # @param id ID of the deal
  # @param user_id ID of the user
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_followers_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_get
  # Get details of a deal
  # Returns details of a specific deal. Note that this also returns some additional fields which are not present when asking for all deals – such as deal age and stay in pipeline stages. Also note that custom fields appear as long hashes in the resulting data. These hashes can be mapped against the &#39;key&#39; value of dealFields.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_mail_messages_get
  # List mail messages associated with a deal
  # Lists mail messages associated with a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @return [nil]
  describe 'deals_id_mail_messages_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_merge_put
  # Merge two deals
  # Merges a deal with another deal.
  # @param id ID of the deal that will be merged
  # @param merge_with_id ID of the deal that the deal will be merged with
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_merge_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_participants_deal_participant_id_delete
  # Delete a participant from a deal
  # Deletes a participant from a deal.
  # @param id ID of the deal
  # @param deal_participant_id ID of the deal participant
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_participants_deal_participant_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_participants_get
  # List participants of a deal
  # Lists participants associated with a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @return [nil]
  describe 'deals_id_participants_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_participants_post
  # Add a participant to a deal
  # Adds a participant to a deal.
  # @param id ID of the deal
  # @param person_id ID of the person
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_participants_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_permitted_users_get
  # List permitted users
  # List users permitted to access a deal
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_level If set, filter results by allowed access level. 1 &#x3D; Read, 2 &#x3D; Write, 3 &#x3D; Read+Write
  # @return [nil]
  describe 'deals_id_permitted_users_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_persons_get
  # List all persons associated with a deal
  # Lists all persons associated with a deal, regardless of whether the person is the primary contact of the deal, or added as a participant.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @return [nil]
  describe 'deals_id_persons_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_products_deal_product_id_put
  # Update product attachment details of the deal-product (a product already attached to a deal)
  # Updates product attachment details.
  # @param id ID of the deal
  # @param deal_product_id ID of the deal-product (the ID of the product attached to the deal)
  # @param item_price Price at which this product will be added to the deal
  # @param quantity Quantity – e.g. how many items of this product will be added to the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :discount_percentage Discount %
  # @option opts [Float] :duration Duration of the product
  # @option opts [Float] :product_variation_id ID of the product variation to use.
  # @option opts [String] :comments Any textual comment associated with this product-deal attachment. Visible and editable in the application UI.
  # @option opts [String] :enabled_flag Whether the product is enabled on the deal or not. This makes it possible to add products to a deal with specific price and discount criteria - but keep them disabled, which refrains them from being included in deal price calculation.
  # @return [nil]
  describe 'deals_id_products_deal_product_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_products_get
  # List products attached to a deal
  # Lists products attached to a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @option opts [String] :include_product_data Whether to fetch product data along with each attached product (1) or not (0, default).
  # @return [nil]
  describe 'deals_id_products_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_products_post
  # Add a product to the deal, eventually creating a new item called a deal-product.
  # Adds a product to the deal.
  # @param id ID of the deal
  # @param product_id ID of the product that will be attached
  # @param item_price Price at which this product will be added to the deal
  # @param quantity Quantity – e.g. how many items of this product will be added to the deal
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :discount_percentage Discount %. If omitted, will be set to 0
  # @option opts [Float] :duration Duration of the product (when product durations are not enabled for the company or if omitted, defaults to 1)
  # @option opts [Float] :product_variation_id ID of the product variation to use. When omitted, no variation will be used.
  # @option opts [String] :comments Any textual comment associated with this product-deal attachment. Visible and editable in the application UI.
  # @option opts [String] :enabled_flag Whether the product is enabled on the deal or not. This makes it possible to add products to a deal with specific price and discount criteria - but keep them disabled, which refrains them from being included in deal price calculation. When omitted, the product will be marked as enabled by default.
  # @return [nil]
  describe 'deals_id_products_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_products_product_attachment_id_delete
  # Delete an attached product from a deal
  # Deletes a product attachment from a deal, using the product_attachment_id.
  # @param id ID of the deal
  # @param product_attachment_id Product attachment ID. This is returned as product_attachment_id after attaching a product to a deal or as id when listing the products attached to a deal.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'deals_id_products_product_attachment_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_id_put
  # Update a deal
  # Updates the properties of a deal.
  # @param id ID of the deal
  # @param [Hash] opts the optional parameters
  # @option opts [String] :title Deal title
  # @option opts [String] :value Value of the deal
  # @option opts [String] :currency Currency of the deal. Accepts a 3-character currency code
  # @option opts [Float] :user_id ID of the user who will be marked as the owner of this deal
  # @option opts [Float] :person_id ID of the person this deal will be associated with
  # @option opts [Float] :org_id ID of the organization this deal will be associated with
  # @option opts [Float] :stage_id ID of the stage this deal will be placed in a pipeline (note that you can&#39;t supply the ID of the pipeline as this will be assigned automatically based on stage_id)
  # @option opts [String] :status open &#x3D; Open, won &#x3D; Won, lost &#x3D; Lost, deleted &#x3D; Deleted
  # @option opts [Float] :probability Deal success probability percentage. Used/shown only when deal_probability for the pipeline of the deal is enabled.
  # @option opts [String] :lost_reason Optional message about why the deal was lost (to be used when status&#x3D;lost)
  # @option opts [String] :visible_to Visibility of the deal. If omitted, visibility will not be changed.&lt;dl class&#x3D;\&quot;fields-list\&quot;&gt;&lt;dt&gt;1&lt;/dt&gt;&lt;dd&gt;Owner &amp;amp; followers (private)&lt;/dd&gt;&lt;dt&gt;3&lt;/dt&gt;&lt;dd&gt;Entire company (shared)&lt;/dd&gt;&lt;/dl&gt;
  # @return [nil]
  describe 'deals_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_post
  # Add a deal
  # Adds a new deal. Note that you can supply additional custom fields along with the request that are not described here. These custom fields are different for each Pipedrive account and can be recognized by long hashes as keys. To determine which custom fields exists, fetch the dealFields and look for &#39;key&#39; values.
  # @param title Deal title
  # @param [Hash] opts the optional parameters
  # @option opts [String] :value Value of the deal. If omitted, value will be set to 0.
  # @option opts [String] :currency Currency of the deal. Accepts a 3-character currency code. If omitted, currency will be set to the default currency of the authorized user.
  # @option opts [Float] :user_id ID of the user who will be marked as the owner of this deal. If omitted, the authorized user ID will be used.
  # @option opts [Float] :person_id ID of the person this deal will be associated with
  # @option opts [Float] :org_id ID of the organization this deal will be associated with
  # @option opts [Float] :stage_id ID of the stage this deal will be placed in a pipeline (note that you can&#39;t supply the ID of the pipeline as this will be assigned automatically based on stage_id). If omitted, the deal will be placed in the first stage of the default pipeline.
  # @option opts [String] :status open &#x3D; Open, won &#x3D; Won, lost &#x3D; Lost, deleted &#x3D; Deleted. If omitted, status will be set to open.
  # @option opts [Float] :probability Deal success probability percentage. Used/shown only when deal_probability for the pipeline of the deal is enabled.
  # @option opts [String] :lost_reason Optional message about why the deal was lost (to be used when status&#x3D;lost)
  # @option opts [String] :add_time Optional creation date &amp; time of the deal in UTC. Requires admin user API token. Format: YYYY-MM-DD HH:MM:SS
  # @option opts [String] :visible_to Visibility of the deal. If omitted, visibility will be set to the default visibility setting of this item type for the authorized user.&lt;dl class&#x3D;\&quot;fields-list\&quot;&gt;&lt;dt&gt;1&lt;/dt&gt;&lt;dd&gt;Owner &amp;amp; followers (private)&lt;/dd&gt;&lt;dt&gt;3&lt;/dt&gt;&lt;dd&gt;Entire company (shared)&lt;/dd&gt;&lt;/dl&gt;
  # @return [nil]
  describe 'deals_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deals_timeline_get
  # Get deals timeline
  # Returns open and won deals, grouped by defined interval of time set in a date-type dealField (field_key) — e.g. when month is the chosen interval, and 3 months are asked starting from  January 1st, 2012, deals are returned grouped into 3 groups — January, February and March — based on the value of the given field_key.
  # @param start_date Date where first interval starts. Format: YYYY-MM-DD
  # @param interval Type of interval.&lt;dl class&#x3D;\&quot;fields-list\&quot;&gt;&lt;dt&gt;day&lt;/dt&gt;&lt;dd&gt;Day&lt;/dd&gt;&lt;dt&gt;week&lt;/dt&gt;&lt;dd&gt;A full week (7 days) starting from start_date&lt;/dd&gt;&lt;dt&gt;month&lt;/dt&gt;&lt;dd&gt;A full month (depending on the number of days in given month) starting from start_date&lt;/dd&gt;&lt;dt&gt;quarter&lt;/dt&gt;&lt;dd&gt;A full quarter (3 months) starting from start_date&lt;/dd&gt;&lt;/dl&gt;
  # @param amount Number of given intervals, starting from start_date, to fetch. E.g. 3 (months).
  # @param field_key The name of the date field by which to get deals by.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :user_id If supplied, only deals matching the given user will be returned.
  # @option opts [Float] :pipeline_id If supplied, only deals matching the given pipeline will be returned.
  # @option opts [Float] :filter_id If supplied, only deals matching the given filter will be returned.
  # @option opts [String] :exclude_deals Whether to exclude deals list (1) or not (0). Note that when deals are excluded, the timeline summary (counts and values) is still returned.
  # @option opts [String] :totals_convert_currency 3-letter currency code of any of the supported currencies. When supplied, totals_converted is returned per each interval which contains the currency-converted total amounts in the given currency. You may also set this parameter to &#39;default_currency&#39; in which case users default currency is used.
  # @return [nil]
  describe 'deals_timeline_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
