=begin
#Pipedrive API v1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Pipedrive::PushNotificationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PushNotificationsApi' do
  before do
    # run before each test
    @instance = Pipedrive::PushNotificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PushNotificationsApi' do
    it 'should create an instance of PushNotificationsApi' do
      expect(@instance).to be_instance_of(Pipedrive::PushNotificationsApi)
    end
  end

  # unit tests for push_notifications_get
  # Get all subscriptions
  # Returns data about all subscriptions. This endpoint is deprecated, use &lt;a href&#x3D;\&quot;#!/Webhooks/get_webhooks\&quot;&gt;Get all webhooks&lt;/a&gt; endpoint instead.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'push_notifications_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for push_notifications_id_delete
  # Delete existing subscription
  # Marks subscription as deleted. This endpoint is deprecated, use &lt;a href&#x3D;\&quot;#!/Webhooks/delete_webhooks_id\&quot;&gt;Delete existing webhook&lt;/a&gt; endpoint instead.
  # @param id ID of the subscription to mark as deleted.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'push_notifications_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for push_notifications_id_get
  # Get details of a subscription
  # Returns data about a specific subscription. This endpoint is deprecated and should not be used anymore.
  # @param id ID of the subscriptions to fetch.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'push_notifications_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for push_notifications_post
  # Create new subscription
  # Creates new subscription and returns details. This endpoint is deprecated, use &lt;a href&#x3D;\&quot;#!/Webhooks/post_webhooks\&quot;&gt;Create a new webhook&lt;/a&gt; endpoint instead.
  # @param subscription_url URL where to send the notifications.
  # @param event What type of notifications to receive (&#39;\\*.\\*&#39; for all events, &#39;added.deal&#39; for any newly added deals, &#39;deleted.persons&#39; for any deleted persons, etc. See https://app.pipedrive.com/push_notifications#dialog:/push_notifications/help for details).
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :user_id ID of the user this push notification will be authorized with. If not set - current authorized user will be used.
  # @option opts [String] :http_auth_user HTTP basic auth username if needed.
  # @option opts [String] :http_auth_password HTTP basic auth password if needed.
  # @return [nil]
  describe 'push_notifications_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
