=begin
#Pipedrive API v1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Pipedrive::RecentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RecentsApi' do
  before do
    # run before each test
    @instance = Pipedrive::RecentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecentsApi' do
    it 'should create an instance of RecentsApi' do
      expect(@instance).to be_instance_of(Pipedrive::RecentsApi)
    end
  end

  # unit tests for recents_get
  # Get recents
  # Returns data about all recent changes occured after given timestamp.
  # @param since_timestamp Timestamp in UTC. Format: YYYY-MM-DD HH:MM:SS
  # @param [Hash] opts the optional parameters
  # @option opts [String] :items Multiple selection of item types to include in query (optional)
  # @option opts [Float] :start Pagination start
  # @option opts [Float] :limit Items shown per page
  # @return [nil]
  describe 'recents_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
