=begin
#Pipedrive API v1

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Pipedrive::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = Pipedrive::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(Pipedrive::WebhooksApi)
    end
  end

  # unit tests for webhooks_get
  # Get all webhooks
  # Returns data about all webhooks of a company.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'webhooks_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_id_delete
  # Delete existing webhook
  # Deletes the specified webhook.
  # @param id ID of the webhook to delete.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'webhooks_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_post
  # Create a new webhook
  # Creates a new webhook and returns its details. Note that specifying an event which triggers the webhook combines 2 parameters - &#39;event_action&#39; and &#39;event_object&#39;. E.g., use &#39;\\*.\\*&#39; for getting notifications about all events, &#39;added.deal&#39; for any newly added deals, &#39;deleted.persons&#39; for any deleted persons, etc. See https://app.pipedrive.com/webhooks for more details.
  # @param subscription_url A full, valid, publicly accessible URL. Determines where to send the notifications. Please note that you cannot use Pipedrive API endpoints as the subscription_url.
  # @param event_action Type of action to receive notifications about. Wildcard will match all supported actions.
  # @param event_object Type of object to receive notifications about. Wildcard will match all supported objects.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :user_id ID of the user this webhook will be authorized with. If not set, current authorized user will be used. Note that this does not filter only certain user&#39;s events — rather, this specifies the user&#39;s permissions under which each event is checked. Events about objects the selected user is not entitled to access are not sent. If you want to receive notifications for all events, a top-level admin user should be used.
  # @option opts [String] :http_auth_user HTTP basic auth username of the subscription URL endpoint (if required).
  # @option opts [String] :http_auth_password HTTP basic auth password of the subscription URL endpoint (if required).
  # @return [nil]
  describe 'webhooks_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
